In [1]:
# Python List as Dynamic Array
mixed_box = [1, "Hello", [3.14, "world"]]
mixed_box.append(99)
print(mixed_box)

[1, 'Hello', [3.14, 'world'], 99]


In [2]:
# Python array Module
import array as ar
score_data = ar.array('i', [10, 20, 30])
score_data.append(40)
print(score_data)

array('i', [10, 20, 30, 40])


In [3]:
# Core Array Operations
import array as ar
temp_readings = ar.array('i', [25, 30, 28])
print(temp_readings[1])
temp_readings.append(35)
print(temp_readings)

30
array('i', [25, 30, 28, 35])


In [4]:
# Indexing & Slicing
import array as ar
numbers = ar.array('i', [1,2,3,4,5,6,7])
print(numbers[2:5])
print(numbers[::-1])

array('i', [3, 4, 5])
array('i', [7, 6, 5, 4, 3, 2, 1])


In [5]:
# Searching & Updating
import array as ar
sales = ar.array('i', [100, 200, 300, 200])
pos = sales.index(200)
sales[pos] = 250
print(sales)

array('i', [100, 250, 300, 200])


In [6]:
# Advanced Array Operations (Count, Reverse, Extend)
import array as ar
log_ids = ar.array('i', [2, 4, 2, 6, 2, 8])

count_2 = log_ids.count(2)
log_ids.reverse()
log_ids.extend([10, 12])

print(count_2)
print(log_ids)

3
array('i', [8, 2, 6, 2, 4, 2, 10, 12])


In [7]:
# NumPy Array (Element-wise Operations)
import numpy as np
vector = np.array([3, 6, 9, 12])
scaled = vector * 3
print(scaled)

[ 9 18 27 36]


In [8]:
# Multi-Dimensional NumPy Array
import numpy as np
grid = np.array([[1, 2], [3, 4]])
doubled = grid * 2
print(doubled)

[[2 4]
 [6 8]]


In [9]:
# Broadcasting Concept
import numpy as np
base = np.array([10, 20, 30])
adder = np.array([5])
result = base + adder
print(result)

[15 25 35]


In [10]:
# Real-World Data Style Example
import numpy as np
daily_sales = np.array([1000, 1200, 900, 1500])
taxed = daily_sales * 1.18
print(taxed)

[1180. 1416. 1062. 1770.]
